# Generated by Django 4.1.7 on 2023-04-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
